Hooks.once('diceSoNiceReady', (dice3d) => {
    dice3d.addSystem({id:"cise",name:"Cise"},true);
    dice3d.addDicePreset({
      type:"d6",
      labels:[
        '1',
        'modules/cise/artwork/s2.png',
        'modules/cise/artwork/s3.png',
		    'modules/cise/artwork/s4.png',
        'modules/cise/artwork/s5.png',
        'modules/cise/artwork/s6.png'
      ],
      bumpMaps:[
        '1',
        'modules/cise/artwork/s2_bump.png',
        'modules/cise/artwork/s3_bump.png',
        'modules/cise/artwork/s4_bump.png',
        'modules/cise/artwork/s5_bump.png',
		    'modules/cise/artwork/s6_bump.png'
      ],
      system:"cise"
    });
});
