Hooks.once('diceSoNiceReady', (dice3d) => {
    dice3d.addSystem({id:"cise",name:"Cise"},true);
    dice3d.addDicePreset({
      type:"d6",
      labels:[
        'modules/cise/artwork/S1.png',
        'modules/cise/artwork/S2.png',
        'modules/cise/artwork/S3.png',
		    'modules/cise/artwork/S4.png',
        'modules/cise/artwork/S5.png',
        'modules/cise/artwork/S6.png'
      ],
      bumpMaps:[
        'modules/cise/artwork/S1_bump.png',
        'modules/cise/artwork/S2_bump.png',
        'modules/cise/artwork/S3_bump.png',
        'modules/cise/artwork/S4_bump.png',
        'modules/cise/artwork/S5_bump.png',
		    'modules/cise/artwork/S6_bump.png'
      ],
      system:"cise"
    });
});
